name: prueba-playgroup

networks:
  main-net:
    driver: bridge

volumes:
  data:
    driver: local

services:
  web:
    image: kooldev/php:8.2-nginx
    container_name: backend-service-prueba-playgroup
    volumes:
      - ".:/app:cached"
      - "./storage:/app/storage"
    ports:
      - "8080:80"
    networks:
      - main-net

  db:
    image: mysql:8.0
    container_name: mysql-service-playgroup
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: prueba_playgroup_db
      MYSQL_ROOT_PASSWORD: root123
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - "data:/var/lib/mysql"
    networks:
      - main-net

  mail:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog-service-prueba-playgroup
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - main-net
